repos:
- hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
  repo: meta
- hooks:
  - id: trailing-whitespace
  - exclude: ^VERSION$
    id: end-of-file-fixer
  - id: check-yaml
  repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
- hooks:
  - id: nixpkgs-fmt
    name: Format Nix Files
  repo: git://github.com/nix-community/nixpkgs-fmt
  rev: v0.9.0
- hooks:
  - args: ["--format=tty", "--shell=bash"]
    files: ^.envrc$
    id: shell-lint
    name: Lint .envrc
    types: [text]
  repo: git://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
